### ISSUE TITLE
Chromecast support

### ISSUE THREAD

**Issue by Kamduras-dev** [watchedcom/watched-js#41] opened 2020-09-14 12:49 UTC
I don't have a problem with your application which I find great but rather a suggestion.

It would be nice to be able to add chromecast support.

Thanks.

**Comment by maximilize** [comment] 2020-09-21 15:35
We are working on it and hope to release such a feature within the next weeks.
Duplicate of #9

**Closed by maximilize** 2020-09-21 15:35 UTC
